name: Code Quality Check
rum-name: (Run by ${{ github.actor }})

on;
  pull_request:
  branches:
    - main

jobs:
  linter:
   name: Link check
   runs-on: ubuntu-latest
   steps:
     - uses: action/checkout@v4
     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 18
     - name: Install dependencies
       run: npm ci
     - name: Run linter
       run: npm run lint

  unit_tests:
    name: Run unit test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: node src/tests/MyUnitTest.js            

